name: 'build-jdk-openj9'
description: 'Build different version of openjdk with openj9'
author: 'Sophia Guo'
inputs:
  version:              # change this
    description: 'openjdk version'
    default: '14'
  user:
    description: 'github repo' # for now it's repo of ibmruntimes/openj9-openjdk-jdk${version}, believe repo of openj9, omr may also be needed?
    default: 'ibmruntimes'
  branch:
    description: 'personal branch'
    default: 'openj9'
outputs:
  BuildOpenJ9JDK: # build jdk images directory
runs:
  using: 'node12'
  main: 'dist/index.js'
