name: "build-jdk-openj9"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      with: 
        version: 8
    - run: cd ${{ env.GITHUB_WORKSPACE }}/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/bin
    - run: ./java -version